# Generated by Django 2.0.1 on 2018-01-14 15:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('insert_datetime', models.DateTimeField(auto_now=True, verbose_name='送信日時')),
            ],
            options={
                'verbose_name_plural': 'コメント',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ファイル名')),
            ],
            options={
                'verbose_name_plural': 'ファイル',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='機能名')),
            ],
            options={
                'verbose_name_plural': '機能',
            },
        ),
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('3', '高'), ('2', '中'), ('1', '低')], max_length=1, verbose_name='優先度')),
                ('send_datetime', models.DateTimeField(auto_now=True, verbose_name='質問日時')),
                ('expect_answer_date', models.DateField(auto_now=True, verbose_name='回答希望日')),
                ('title', models.CharField(max_length=50, verbose_name='質問概要')),
                ('detail', models.TextField(verbose_name='質問詳細')),
                ('answer', models.TextField(null=True, verbose_name='回答詳細')),
                ('answer_datetime', models.DateTimeField(null=True, verbose_name='回答日時')),
                ('status', models.CharField(choices=[('1', '起票'), ('2', '回答完了'), ('3', '確認完了'), ('4', '保留'), ('5', '廃棄')], default='1', max_length=1, verbose_name='ステータス')),
                ('expect_answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expect_answer_user', to=settings.AUTH_USER_MODEL, verbose_name='回答希望者')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.Function', verbose_name='機能')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='質問者')),
            ],
            options={
                'verbose_name_plural': 'QA',
            },
        ),
        migrations.CreateModel(
            name='QaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Qa', verbose_name='QA')),
            ],
            options={
                'verbose_name_plural': 'QAタグ',
            },
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='サブシステム名')),
            ],
            options={
                'verbose_name_plural': 'サブシステム',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='システム名')),
                ('start_date', models.DateField(default=datetime.date, verbose_name='開始日')),
                ('end_date', models.DateField(null=True, verbose_name='終了日')),
            ],
            options={
                'verbose_name_plural': 'システム',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(choices=[('1', '管理人'), ('2', '一般ユーザ')], default='2', max_length=1, verbose_name='権限')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.System', verbose_name='システム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': 'システムユーザ',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ名')),
            ],
            options={
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.AddField(
            model_name='subsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.System', verbose_name='システム'),
        ),
        migrations.AddField(
            model_name='qatag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tag', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='function',
            name='sub_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.SubSystem', verbose_name='サブシステム'),
        ),
        migrations.AddField(
            model_name='file',
            name='qa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Qa', verbose_name='QA'),
        ),
        migrations.AddField(
            model_name='comment',
            name='qa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Qa', verbose_name='QA'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='送信者'),
        ),
    ]
