# Generated by Django 2.0.1 on 2018-01-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='qa',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
