# Generated by Django 2.0.1 on 2018-01-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20180121_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa',
            options={'ordering': ['-update_datetime'], 'verbose_name_plural': 'QA'},
        ),
    ]
