# Generated by Django 2.0.1 on 2018-01-21 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0006_auto_20180121_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='マネジャー'),
        ),
    ]
