# Generated by Django 2.0.1 on 2018-01-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20180121_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='マネジャー'),
        ),
    ]
