# Generated by Django 2.0.1 on 2018-01-21 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20180121_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='システムユーザ'),
        ),
    ]
