# Generated by Django 2.0.1 on 2018-01-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20180121_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='system',
        ),
        migrations.RemoveField(
            model_name='function',
            name='sub_system',
        ),
        migrations.AddField(
            model_name='function',
            name='system',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='mainsite.System', verbose_name='システム'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubSystem',
        ),
    ]
