# Generated by Django 2.0.1 on 2018-01-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20180122_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='system',
        ),
        migrations.AlterField(
            model_name='qa',
            name='function',
            field=models.CharField(max_length=100, verbose_name='機能'),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
