# Generated by Django 2.0.1 on 2018-01-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20180122_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.System', verbose_name='システム'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qa',
            name='expect_answer_date',
            field=models.DateField(verbose_name='回答希望日'),
        ),
    ]
